create table book (
      id bigint generated by default as identity (start with 1)
    , title varchar(255)
    , author varchar(255)
    , primary key (id)
);
insert into book(id, title, author) values (default, 'Mostly Harmless', 'Douglas Adams');
insert into book(id, title, author) values (default, 'Sirens of Titan', 'Kurt Vonnegut');
insert into book(id, title, author) values (default, 'Mother night', 'Kurt Vonnegut');
