create table book (
      id bigint generated by default as identity (start with 1)
    , title varchar(255)
    , author varchar(255)
    , synopsis varchar(500)
    , primary key (id)
);

create table users (
	 id bigint generated by default as identity (start with 1),
	 name varchar(255),
	 email varchar(255),
	 password varchar(255),
	 primary key(id)
);

insert into book(id, title, author) values (default, 'Mostly Harmless', 'Douglas Adams');
insert into book(id, title, author) values (default, 'Sirens of Titan', 'Kurt Vonnegut');
insert into book(id, title, author) values (default, 'Mother night', 'Kurt Vonnegut');


insert into users(id, name, email, password) values (default, 'joe', 'joe@a.com', '1234');
insert into users(id, name, email, password) values (default, 'joe2', 'joe2@a.com', '1234');
insert into users(id, name, email, password) values (default, 'joe3', 'joe3@be.com', '1234');
insert into users(id, name, email, password) values (default, 'korte', 'joe3@alma.com', '1234');

